import type { PresetBackendIntensity } from "./presetIntensity";

type AddedPreset = {
  id: string;
  label: string;
  category:
    | "lineart"
    | "photo-edge"
    | "scan"
    | "logo"
    | "diagram"
    | "stroke"
    | "layered";
  backendIntensity?: PresetBackendIntensity;
  settings: Record<string, unknown>;
};

export const TRACE_PRESET_ADDITIONS: AddedPreset[] = [
  {
    id: "line-clean",
    label: "Lineart - Clean",
    category: "lineart",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 224,
      turdSize: 3,
      optTolerance: 0.34,
      turnPolicy: "majority",
      lineColor: "#000000",
      invert: false,
    },
  },
  {
    id: "line-smooth",
    label: "Lineart - Smooth",
    category: "lineart",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 218,
      turdSize: 4,
      optTolerance: 0.52,
      turnPolicy: "majority",
    },
  },
  {
    id: "line-sharp",
    label: "Lineart - Sharp",
    category: "lineart",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 230,
      turdSize: 1,
      optTolerance: 0.2,
      turnPolicy: "minority",
    },
  },
  {
    id: "line-thin",
    label: "Lineart - Thin",
    category: "lineart",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 240,
      turdSize: 1,
      optTolerance: 0.24,
      turnPolicy: "minority",
    },
  },
  {
    id: "line-thick",
    label: "Lineart - Thick",
    category: "lineart",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 206,
      turdSize: 4,
      optTolerance: 0.44,
      turnPolicy: "black",
    },
  },
  {
    id: "line-tiny-detail",
    label: "Lineart - Tiny Detail",
    category: "lineart",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 236,
      turdSize: 0,
      optTolerance: 0.18,
      turnPolicy: "minority",
      maxTraceSide: 2400,
    },
  },
  {
    id: "line-low-noise",
    label: "Lineart - Low Noise",
    category: "lineart",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 222,
      turdSize: 6,
      optTolerance: 0.45,
      turnPolicy: "majority",
      minIslandPx: 8,
    },
  },
  {
    id: "line-rounded",
    label: "Lineart - Rounded",
    category: "lineart",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 218,
      turdSize: 3,
      optTolerance: 0.7,
      turnPolicy: "majority",
    },
  },
  {
    id: "line-cut-friendly",
    label: "Lineart - Cut Friendly",
    category: "lineart",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 216,
      turdSize: 7,
      optTolerance: 0.6,
      turnPolicy: "black",
      minIslandPx: 12,
      holeFillPx: 10,
      gapCloseStrength: 1,
    },
  },
  {
    id: "drawing-ink",
    label: "Drawing - Ink",
    category: "lineart",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 214,
      turdSize: 3,
      optTolerance: 0.34,
      turnPolicy: "black",
    },
  },
  {
    id: "drawing-smooth-ink",
    label: "Drawing - Smooth Ink",
    category: "lineart",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 212,
      turdSize: 4,
      optTolerance: 0.55,
      turnPolicy: "majority",
    },
  },
  {
    id: "drawing-texture",
    label: "Drawing - Preserve Texture",
    category: "lineart",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 232,
      turdSize: 1,
      optTolerance: 0.2,
      turnPolicy: "minority",
      maxTraceSide: 2200,
    },
  },
  {
    id: "drawing-bold-strokes",
    label: "Drawing - Bold Strokes",
    category: "lineart",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 204,
      turdSize: 4,
      optTolerance: 0.42,
      turnPolicy: "black",
    },
  },
  {
    id: "sketch-pencil",
    label: "Sketch - Pencil",
    category: "lineart",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.8,
      edgeBoost: 1.05,
      threshold: 220,
      turdSize: 2,
      optTolerance: 0.3,
      turnPolicy: "minority",
    },
  },
  {
    id: "sketch-dark-pencil",
    label: "Sketch - Dark Pencil",
    category: "lineart",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.65,
      edgeBoost: 1.3,
      threshold: 228,
      turdSize: 2,
      optTolerance: 0.28,
      turnPolicy: "minority",
    },
  },
  {
    id: "sketch-faded-pencil",
    label: "Sketch - Faded Pencil",
    category: "lineart",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.1,
      edgeBoost: 1.55,
      threshold: 232,
      turdSize: 2,
      optTolerance: 0.32,
      turnPolicy: "minority",
      brightness: 8,
      contrast: 18,
    },
  },
  {
    id: "sketch-fine-lines",
    label: "Sketch - Fine Lines",
    category: "lineart",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.45,
      edgeBoost: 1.25,
      threshold: 236,
      turdSize: 1,
      optTolerance: 0.22,
      turnPolicy: "minority",
      maxTraceSide: 2200,
    },
  },
  {
    id: "sketch-clean-lines",
    label: "Sketch - Clean Lines",
    category: "lineart",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.9,
      edgeBoost: 1.15,
      threshold: 226,
      turdSize: 4,
      optTolerance: 0.4,
      turnPolicy: "majority",
      minIslandPx: 6,
    },
  },
  {
    id: "photo-edge-minimal",
    label: "Photo Edge - Minimal",
    category: "photo-edge",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.6,
      edgeBoost: 0.85,
      threshold: 214,
      turdSize: 5,
      optTolerance: 0.55,
      turnPolicy: "majority",
    },
  },
  {
    id: "photo-edge-contour",
    label: "Photo Edge - Contour",
    category: "photo-edge",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.0,
      edgeBoost: 1.2,
      threshold: 224,
      turdSize: 3,
      optTolerance: 0.42,
      turnPolicy: "majority",
    },
  },
  {
    id: "photo-edge-strong",
    label: "Photo Edge - Strong",
    category: "photo-edge",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.65,
      edgeBoost: 1.65,
      threshold: 232,
      turdSize: 2,
      optTolerance: 0.36,
      turnPolicy: "black",
      edgeThreshold: 24,
      edgeThickness: 2,
    },
  },
  {
    id: "photo-edge-fine",
    label: "Photo Edge - Fine",
    category: "photo-edge",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.45,
      edgeBoost: 1.3,
      threshold: 236,
      turdSize: 1,
      optTolerance: 0.25,
      turnPolicy: "minority",
      maxTraceSide: 2200,
    },
  },
  {
    id: "photo-edge-portrait",
    label: "Photo Edge - Portrait",
    category: "photo-edge",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.85,
      edgeBoost: 1.18,
      threshold: 222,
      turdSize: 2,
      optTolerance: 0.34,
      turnPolicy: "majority",
      edgeThreshold: 18,
    },
  },
  {
    id: "photo-edge-low-light",
    label: "Photo Edge - Low Light",
    category: "photo-edge",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.1,
      edgeBoost: 1.55,
      threshold: 230,
      turdSize: 3,
      optTolerance: 0.4,
      turnPolicy: "majority",
      brightness: 10,
      contrast: 22,
    },
  },
  {
    id: "photo-edge-high-contrast",
    label: "Photo Edge - High Contrast",
    category: "photo-edge",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.75,
      edgeBoost: 1.45,
      threshold: 234,
      turdSize: 2,
      optTolerance: 0.38,
      turnPolicy: "black",
      contrast: 24,
    },
  },
  {
    id: "photo-edge-smooth",
    label: "Photo Edge - Smooth",
    category: "photo-edge",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.45,
      edgeBoost: 1.05,
      threshold: 220,
      turdSize: 5,
      optTolerance: 0.62,
      turnPolicy: "majority",
    },
  },
  {
    id: "photo-edge-poster",
    label: "Photo Edge - Poster",
    category: "photo-edge",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.9,
      edgeBoost: 1.55,
      threshold: 238,
      turdSize: 3,
      optTolerance: 0.5,
      turnPolicy: "black",
      edgeThickness: 2,
    },
  },
  {
    id: "photo-edge-silhouette",
    label: "Photo Edge - Silhouette",
    category: "photo-edge",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.25,
      edgeBoost: 1.4,
      threshold: 242,
      turdSize: 5,
      optTolerance: 0.55,
      turnPolicy: "black",
    },
  },
  {
    id: "scan-faded",
    label: "Scan - Faded",
    category: "scan",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 238,
      turdSize: 3,
      optTolerance: 0.32,
      turnPolicy: "minority",
      brightness: 6,
      contrast: 18,
    },
  },
  {
    id: "scan-shadow-cleanup",
    label: "Scan - Shadow Cleanup",
    category: "scan",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 218,
      turdSize: 5,
      optTolerance: 0.45,
      turnPolicy: "majority",
      brightness: 8,
      contrast: 16,
      minIslandPx: 10,
    },
  },
  {
    id: "scan-ink-cleanup",
    label: "Scan - Ink Cleanup",
    category: "scan",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 224,
      turdSize: 5,
      optTolerance: 0.35,
      turnPolicy: "majority",
      minIslandPx: 6,
    },
  },
  {
    id: "scan-fine-marks",
    label: "Scan - Fine Marks",
    category: "scan",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 236,
      turdSize: 1,
      optTolerance: 0.22,
      turnPolicy: "minority",
    },
  },
  {
    id: "scan-text-marks",
    label: "Scan - Text Marks",
    category: "scan",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 226,
      turdSize: 2,
      optTolerance: 0.24,
      turnPolicy: "minority",
      holeFillPx: 6,
    },
  },
  {
    id: "scan-notebook",
    label: "Scan - Notebook",
    category: "scan",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 232,
      turdSize: 3,
      optTolerance: 0.32,
      turnPolicy: "majority",
      brightness: 8,
      contrast: 18,
      minIslandPx: 8,
    },
  },
  {
    id: "scan-high-contrast",
    label: "Scan - High Contrast",
    category: "scan",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 214,
      turdSize: 4,
      optTolerance: 0.35,
      turnPolicy: "black",
      contrast: 25,
    },
  },
  {
    id: "whiteboard-marker",
    label: "Whiteboard - Marker",
    category: "scan",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.1,
      edgeBoost: 1.25,
      threshold: 224,
      turdSize: 3,
      optTolerance: 0.38,
      turnPolicy: "majority",
      lineColor: "#111827",
    },
  },
  {
    id: "whiteboard-clean",
    label: "Whiteboard - Clean",
    category: "scan",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.35,
      edgeBoost: 1.1,
      threshold: 222,
      turdSize: 5,
      optTolerance: 0.5,
      turnPolicy: "majority",
      minIslandPx: 10,
    },
  },
  {
    id: "whiteboard-low-glare",
    label: "Whiteboard - Low Glare",
    category: "scan",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.5,
      edgeBoost: 1.25,
      threshold: 228,
      turdSize: 4,
      optTolerance: 0.42,
      turnPolicy: "majority",
      brightness: 8,
      contrast: 14,
    },
  },
  {
    id: "logo-sharp",
    label: "Logo - Sharp",
    category: "logo",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 226,
      turdSize: 1,
      optTolerance: 0.18,
      turnPolicy: "minority",
      lineColor: "#000000",
      transparent: true,
    },
  },
  {
    id: "logo-smooth",
    label: "Logo - Smooth",
    category: "logo",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 214,
      turdSize: 3,
      optTolerance: 0.5,
      turnPolicy: "majority",
      lineColor: "#000000",
      transparent: true,
    },
  },
  {
    id: "logo-bold",
    label: "Logo - Bold",
    category: "logo",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 204,
      turdSize: 3,
      optTolerance: 0.34,
      turnPolicy: "black",
      lineColor: "#000000",
      transparent: true,
    },
  },
  {
    id: "logo-flat-mark",
    label: "Logo - Flat Mark",
    category: "logo",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 216,
      turdSize: 4,
      optTolerance: 0.42,
      turnPolicy: "majority",
      transparent: true,
    },
  },
  {
    id: "logo-thin-detail",
    label: "Logo - Thin Detail",
    category: "logo",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 236,
      turdSize: 1,
      optTolerance: 0.2,
      turnPolicy: "minority",
      transparent: true,
    },
  },
  {
    id: "logo-clean-transparent",
    label: "Logo - Clean Transparent",
    category: "logo",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 220,
      turdSize: 3,
      optTolerance: 0.3,
      turnPolicy: "majority",
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
    },
  },
  {
    id: "logo-white-remove",
    label: "Logo - White Remove",
    category: "logo",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 218,
      turdSize: 3,
      optTolerance: 0.32,
      turnPolicy: "majority",
      removeWhite: true,
      transparent: true,
    },
  },
  {
    id: "icon-bold",
    label: "Icon - Bold",
    category: "logo",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 206,
      turdSize: 3,
      optTolerance: 0.32,
      turnPolicy: "black",
      transparent: true,
    },
  },
  {
    id: "icon-monoline",
    label: "Icon - Monoline",
    category: "logo",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 228,
      turdSize: 2,
      optTolerance: 0.26,
      turnPolicy: "minority",
      transparent: true,
    },
  },
  {
    id: "icon-app-mark",
    label: "Icon - App Mark",
    category: "logo",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 212,
      turdSize: 4,
      optTolerance: 0.4,
      turnPolicy: "majority",
      transparent: true,
    },
  },
  {
    id: "icon-simple",
    label: "Icon - Simple",
    category: "logo",
    backendIntensity: "lightning-fast",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 208,
      turdSize: 7,
      optTolerance: 0.65,
      turnPolicy: "majority",
      maxTraceSide: 1200,
      transparent: true,
    },
  },
  {
    id: "diagram-technical",
    label: "Diagram - Technical",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 224,
      turdSize: 2,
      optTolerance: 0.22,
      turnPolicy: "minority",
      lineColor: "#111827",
    },
  },
  {
    id: "diagram-thin-strokes",
    label: "Diagram - Thin Strokes",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 238,
      turdSize: 1,
      optTolerance: 0.2,
      turnPolicy: "minority",
      lineColor: "#111827",
    },
  },
  {
    id: "diagram-bold-strokes",
    label: "Diagram - Bold Strokes",
    category: "diagram",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 208,
      turdSize: 3,
      optTolerance: 0.34,
      turnPolicy: "black",
      lineColor: "#111827",
    },
  },
  {
    id: "diagram-map-lines",
    label: "Diagram - Map Lines",
    category: "diagram",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.55,
      edgeBoost: 1.2,
      threshold: 232,
      turdSize: 1,
      optTolerance: 0.24,
      turnPolicy: "minority",
      maxTraceSide: 2200,
    },
  },
  {
    id: "diagram-blueprint-clean",
    label: "Diagram - Blueprint Clean",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 228,
      turdSize: 3,
      optTolerance: 0.34,
      turnPolicy: "minority",
      invert: true,
      lineColor: "#38bdf8",
      transparent: false,
      bgColor: "#0f172a",
    },
  },
  {
    id: "blueprint-fine",
    label: "Blueprint - Fine",
    category: "diagram",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 238,
      turdSize: 1,
      optTolerance: 0.2,
      turnPolicy: "minority",
      invert: true,
      lineColor: "#7dd3fc",
      transparent: false,
      bgColor: "#0b1020",
    },
  },
  {
    id: "blueprint-bold",
    label: "Blueprint - Bold",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 214,
      turdSize: 3,
      optTolerance: 0.38,
      turnPolicy: "black",
      invert: true,
      lineColor: "#38bdf8",
      transparent: false,
      bgColor: "#0b1020",
    },
  },
  {
    id: "stamp-rubber",
    label: "Stamp - Rubber",
    category: "diagram",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 196,
      turdSize: 6,
      optTolerance: 0.55,
      turnPolicy: "black",
      lineColor: "#111827",
    },
  },
  {
    id: "stencil-simple",
    label: "Stencil - Simple",
    category: "diagram",
    backendIntensity: "lightning-fast",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 210,
      turdSize: 8,
      optTolerance: 0.68,
      turnPolicy: "majority",
      maxTraceSide: 1200,
    },
  },
  {
    id: "stencil-bold",
    label: "Stencil - Bold",
    category: "diagram",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 202,
      turdSize: 7,
      optTolerance: 0.6,
      turnPolicy: "black",
    },
  },
  {
    id: "cricut-clean-cut",
    label: "Cricut - Clean Cut",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 216,
      turdSize: 7,
      optTolerance: 0.62,
      turnPolicy: "majority",
      minIslandPx: 14,
      holeFillPx: 10,
      gapCloseStrength: 1,
      transparent: true,
    },
  },
  {
    id: "cricut-smooth-cut",
    label: "Cricut - Smooth Cut",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 212,
      turdSize: 8,
      optTolerance: 0.75,
      turnPolicy: "majority",
      minIslandPx: 12,
      holeFillPx: 12,
      transparent: true,
    },
  },
  {
    id: "cricut-fine-detail",
    label: "Cricut - Fine Detail",
    category: "diagram",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 228,
      turdSize: 2,
      optTolerance: 0.3,
      turnPolicy: "minority",
      minIslandPx: 3,
      maxTraceSide: 2200,
      transparent: true,
    },
  },
  {
    id: "cricut-bold-cut",
    label: "Cricut - Bold Cut",
    category: "diagram",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 202,
      turdSize: 7,
      optTolerance: 0.58,
      turnPolicy: "black",
      minIslandPx: 10,
      transparent: true,
    },
  },
  {
    id: "vinyl-simple",
    label: "Vinyl - Simple",
    category: "diagram",
    backendIntensity: "lightning-fast",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 208,
      turdSize: 9,
      optTolerance: 0.75,
      turnPolicy: "majority",
      maxTraceSide: 1200,
      transparent: true,
    },
  },
  {
    id: "vinyl-clean",
    label: "Vinyl - Clean",
    category: "diagram",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 214,
      turdSize: 8,
      optTolerance: 0.66,
      turnPolicy: "majority",
      minIslandPx: 16,
      transparent: true,
    },
  },
  {
    id: "vinyl-bold",
    label: "Vinyl - Bold",
    category: "diagram",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 202,
      turdSize: 8,
      optTolerance: 0.6,
      turnPolicy: "black",
      minIslandPx: 12,
      transparent: true,
    },
  },
  {
    id: "sticker-clean-edge",
    label: "Sticker - Clean Edge",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.9,
      edgeBoost: 1.25,
      threshold: 226,
      turdSize: 5,
      optTolerance: 0.55,
      turnPolicy: "majority",
      minIslandPx: 10,
      transparent: true,
    },
  },
  {
    id: "sticker-thick-outline",
    label: "Sticker - Thick Outline",
    category: "diagram",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 0.75,
      edgeBoost: 1.55,
      threshold: 232,
      turdSize: 5,
      optTolerance: 0.62,
      turnPolicy: "black",
      edgeThickness: 3,
      transparent: true,
    },
  },
  {
    id: "sticker-smooth",
    label: "Sticker - Smooth",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1.2,
      edgeBoost: 1.15,
      threshold: 224,
      turdSize: 6,
      optTolerance: 0.7,
      turnPolicy: "majority",
      minIslandPx: 12,
      transparent: true,
    },
  },
  {
    id: "laser-thin-cut",
    label: "Laser - Thin Cut",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 236,
      turdSize: 1,
      optTolerance: 0.24,
      turnPolicy: "minority",
      lineColor: "#000000",
      transparent: true,
    },
  },
  {
    id: "laser-smooth-cut",
    label: "Laser - Smooth Cut",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 222,
      turdSize: 5,
      optTolerance: 0.58,
      turnPolicy: "majority",
      minIslandPx: 8,
      transparent: true,
    },
  },
  {
    id: "transparent-clean",
    label: "Transparent - Clean",
    category: "diagram",
    backendIntensity: "lightning-fast",
    settings: {
      traceMode: "single",
      transparent: true,
      bgColor: "#ffffff",
      backgroundAlpha: 1,
    },
  },
  {
    id: "white-remove-soft",
    label: "White Remove - Soft",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      removeWhite: true,
      transparent: true,
      threshold: 222,
      turdSize: 3,
      optTolerance: 0.35,
    },
  },
  {
    id: "white-remove-strong",
    label: "White Remove - Strong",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      removeWhite: true,
      transparent: true,
      threshold: 210,
      turdSize: 6,
      optTolerance: 0.5,
      minIslandPx: 12,
    },
  },
  {
    id: "invert-white-lines",
    label: "Invert - White Lines",
    category: "diagram",
    backendIntensity: "extreme-speed",
    settings: {
      traceMode: "single",
      preprocess: "none",
      threshold: 224,
      turdSize: 2,
      optTolerance: 0.3,
      turnPolicy: "minority",
      invert: true,
      lineColor: "#ffffff",
      transparent: false,
      bgColor: "#0b1020",
    },
  },
  {
    id: "invert-chalkboard",
    label: "Invert - Chalkboard",
    category: "diagram",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "single",
      preprocess: "edge",
      blurSigma: 1,
      edgeBoost: 1.15,
      threshold: 226,
      turdSize: 3,
      optTolerance: 0.42,
      turnPolicy: "majority",
      invert: true,
      lineColor: "#f8fafc",
      transparent: false,
      bgColor: "#111827",
    },
  },
  {
    id: "color-blue-line",
    label: "Color - Blue Line",
    category: "diagram",
    backendIntensity: "lightning-fast",
    settings: {
      traceMode: "single",
      lineColor: "#0b2dff",
      invert: false,
    },
  },
  {
    id: "color-red-line",
    label: "Color - Red Line",
    category: "diagram",
    backendIntensity: "lightning-fast",
    settings: {
      traceMode: "single",
      lineColor: "#dc2626",
      invert: false,
    },
  },
  {
    id: "color-gray-line",
    label: "Color - Gray Line",
    category: "diagram",
    backendIntensity: "lightning-fast",
    settings: {
      traceMode: "single",
      lineColor: "#475569",
      invert: false,
    },
  },
  {
    id: "layered-3-color",
    label: "Layered - 3 Color",
    category: "layered",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 3,
      layerMaxTraceSide: 1200,
      minRegionPercent: 0.6,
      layerOptTolerance: 0.65,
      layerTurdSize: 7,
      layerTurnPolicy: "majority",
      posterize: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 24,
    },
  },
  {
    id: "layered-4-color",
    label: "Layered - 4 Color",
    category: "layered",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 4,
      layerMaxTraceSide: 1400,
      minRegionPercent: 0.45,
      layerOptTolerance: 0.55,
      layerTurdSize: 5,
      layerTurnPolicy: "majority",
      posterize: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 16,
    },
  },
  {
    id: "layered-6-color",
    label: "Layered - 6 Color",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 6,
      layerMaxTraceSide: 1700,
      minRegionPercent: 0.25,
      layerOptTolerance: 0.42,
      layerTurdSize: 3,
      layerTurnPolicy: "majority",
      posterize: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 10,
    },
  },
  {
    id: "layered-8-color",
    label: "Layered - 8 Color",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 8,
      layerCount: 8,
      requestedPaletteCount: 8,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 0.8,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 2000,
      minRegionPercent: 0.2,
      layerOptTolerance: 0.32,
      layerTurdSize: 2,
      layerTurnPolicy: "minority",
      posterize: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 8,
      minIslandPx: 10,
      holeFillPx: 8,
      sortLayersBy: "area",
    },
  },
  {
    id: "layered-poster",
    label: "Layered - Poster",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 6,
      layerCount: 6,
      requestedPaletteCount: 6,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "bt709",
      layerMaxTraceSide: 1800,
      minRegionPercent: 0.25,
      layerOptTolerance: 0.48,
      layerTurdSize: 4,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 5,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 18,
      minIslandPx: 16,
      holeFillPx: 14,
      sortLayersBy: "area",
    },
  },
  {
    id: "layered-sticker",
    label: "Layered - Sticker",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 7,
      layerMaxTraceSide: 1700,
      minRegionPercent: 0.3,
      layerOptTolerance: 0.45,
      layerTurdSize: 4,
      layerTurnPolicy: "majority",
      posterize: true,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 12,
    },
  },
  {
    id: "layered-logo",
    label: "Layered - Logo",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 5,
      layerMaxTraceSide: 1800,
      minRegionPercent: 0.18,
      layerOptTolerance: 0.26,
      layerTurdSize: 2,
      layerTurnPolicy: "minority",
      posterize: false,
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 6,
    },
  },
  {
    id: "layered-smooth",
    label: "Layered - Smooth",
    category: "layered",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 5,
      layerMaxTraceSide: 1500,
      minRegionPercent: 0.45,
      layerOptTolerance: 0.7,
      layerTurdSize: 7,
      layerTurnPolicy: "majority",
      posterize: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 20,
    },
  },
  {
    id: "layered-detail",
    label: "Layered - Detail",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 28,
      requestedPaletteCount: 28,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1700,
      minRegionPercent: 0.05,
      layerOptTolerance: 0.32,
      layerTurdSize: 2,
      layerTurnPolicy: "minority",
      posterize: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 5,
      minIslandPx: 8,
      holeFillPx: 8,
      sortLayersBy: "area",
    },
  },
  {
    id: "layered-cut-friendly",
    label: "Layered - Cut Friendly",
    category: "layered",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 4,
      layerMaxTraceSide: 1400,
      minRegionPercent: 0.75,
      layerOptTolerance: 0.75,
      layerTurdSize: 8,
      layerTurnPolicy: "majority",
      posterize: true,
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 28,
    },
  },
  {
    id: "layered-low-noise",
    label: "Layered - Low Noise",
    category: "layered",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 5,
      layerMaxTraceSide: 1400,
      minRegionPercent: 0.7,
      layerOptTolerance: 0.65,
      layerTurdSize: 8,
      layerTurnPolicy: "majority",
      posterize: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 26,
    },
  },
  {
    id: "layered-bold-shapes",
    label: "Layered - Bold Shapes",
    category: "layered",
    backendIntensity: "high-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 3,
      layerMaxTraceSide: 1200,
      minRegionPercent: 0.9,
      layerOptTolerance: 0.78,
      layerTurdSize: 9,
      layerTurnPolicy: "black",
      posterize: true,
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 32,
    },
  },
  {
    id: "layered-soft-poster",
    label: "Layered - Soft Poster",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 12,
      requestedPaletteCount: 12,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 0.8,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1700,
      minRegionPercent: 0.1,
      layerOptTolerance: 0.6,
      layerTurdSize: 5,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 4,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 18,
      minIslandPx: 14,
      holeFillPx: 16,
      sortLayersBy: "area",
    },
  },
  {
    id: "layered-flat-color",
    label: "Layered - Flat Color",
    category: "layered",
    backendIntensity: "insanely-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 16,
      requestedPaletteCount: 16,
      layerBuildMode: "per-color-cutout",
      layerOverlapPx: 0,
      gapFill: "close-small-gaps",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1500,
      minRegionPercent: 0.07,
      layerOptTolerance: 0.5,
      layerTurdSize: 4,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 11,
      minIslandPx: 10,
      holeFillPx: 12,
      sortLayersBy: "area",
    },
  },
  {
    id: "ui-mockup-app-screen",
    label: "UI Mockup / App Screen",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 28,
      requestedPaletteCount: 28,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1600,
      minRegionPercent: 0.05,
      layerOptTolerance: 0.32,
      layerTurdSize: 2,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 7,
      minIslandPx: 8,
      holeFillPx: 10,
      sortLayersBy: "area",
    },
  },
  {
    id: "photo-many-colors",
    label: "Photo Many Colors",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 32,
      layerCount: 10,
      requestedPaletteCount: 32,
      layerBuildMode: "per-color-cutout",
      layerOverlapPx: 0,
      gapFill: "close-small-gaps",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 820,
      minRegionPercent: 0.08,
      layerOptTolerance: 0.62,
      layerTurdSize: 8,
      layerTurnPolicy: "minority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 5,
      minIslandPx: 18,
      holeFillPx: 12,
      sortLayersBy: "area",
    },
  },
  {
    id: "filled-layers-smooth",
    label: "Filled Layers - Smooth",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 20,
      requestedPaletteCount: 20,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1500,
      minRegionPercent: 0.07,
      layerOptTolerance: 0.42,
      layerTurdSize: 3,
      layerTurnPolicy: "majority",
      posterize: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 8,
      minIslandPx: 9,
      holeFillPx: 10,
      sortLayersBy: "area",
    },
  },
  {
    id: "filled-layers-separate-colors",
    label: "Filled Layers - Separate Colors",
    category: "layered",
    backendIntensity: "insanely-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 16,
      requestedPaletteCount: 16,
      layerBuildMode: "per-color-cutout",
      layerOverlapPx: 0,
      gapFill: "none",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1400,
      minRegionPercent: 0.08,
      layerOptTolerance: 0.42,
      layerTurdSize: 3,
      layerTurnPolicy: "minority",
      posterize: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 5,
      minIslandPx: 10,
      holeFillPx: 0,
      sortLayersBy: "area",
    },
  },
  {
    id: "clean-color-sticker",
    label: "Clean Color Sticker",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 20,
      requestedPaletteCount: 20,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1500,
      minRegionPercent: 0.07,
      layerOptTolerance: 0.4,
      layerTurdSize: 3,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 8,
      minIslandPx: 10,
      holeFillPx: 12,
      sortLayersBy: "area",
    },
  },
  {
    id: "layered-color-ink-outline",
    label: "Layered Color + Ink Outline",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 18,
      requestedPaletteCount: 18,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1450,
      minRegionPercent: 0.06,
      layerOptTolerance: 0.36,
      layerTurdSize: 3,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 8,
      minIslandPx: 8,
      holeFillPx: 6,
      sortLayersBy: "area",
      fillStrokeWidth: 1.6,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "cartoon-fill-stroke",
    label: "Cartoon Fill + Stroke",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 14,
      requestedPaletteCount: 14,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1350,
      minRegionPercent: 0.09,
      layerOptTolerance: 0.5,
      layerTurdSize: 4,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 10,
      minIslandPx: 10,
      holeFillPx: 8,
      sortLayersBy: "area",
      fillStrokeWidth: 2.25,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "sticker-fill-stroke-detail",
    label: "Sticker Fill + Stroke Detail",
    category: "layered",
    backendIntensity: "insanely-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 22,
      requestedPaletteCount: 22,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1550,
      minRegionPercent: 0.05,
      layerOptTolerance: 0.34,
      layerTurdSize: 2,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 6,
      minIslandPx: 7,
      holeFillPx: 5,
      sortLayersBy: "area",
      fillStrokeWidth: 1.25,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "premium-cartoon-fill-ink",
    label: "Premium Cartoon Fill + Ink",
    category: "layered",
    backendIntensity: "insanely-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 26,
      requestedPaletteCount: 26,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1700,
      minRegionPercent: 0.04,
      layerOptTolerance: 0.28,
      layerTurdSize: 2,
      layerTurnPolicy: "minority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 5,
      minIslandPx: 6,
      holeFillPx: 4,
      sortLayersBy: "area",
      fillStrokeWidth: 1.8,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "sticker-soft-fill-outline",
    label: "Sticker Soft Fill + Outline",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 16,
      requestedPaletteCount: 16,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1.2,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1450,
      minRegionPercent: 0.08,
      layerOptTolerance: 0.56,
      layerTurdSize: 4,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 10,
      minIslandPx: 12,
      holeFillPx: 14,
      sortLayersBy: "area",
      fillStrokeWidth: 2.6,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "sticker-bold-ink-fill",
    label: "Sticker Bold Ink Fill",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 14,
      requestedPaletteCount: 14,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1.25,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1350,
      minRegionPercent: 0.11,
      layerOptTolerance: 0.58,
      layerTurdSize: 5,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 13,
      minIslandPx: 14,
      holeFillPx: 16,
      sortLayersBy: "area",
      fillStrokeWidth: 3.25,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "transparent-sticker-clean-color",
    label: "Transparent Sticker Clean Color",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 12,
      requestedPaletteCount: 12,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1350,
      minRegionPercent: 0.12,
      layerOptTolerance: 0.62,
      layerTurdSize: 5,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 14,
      minIslandPx: 14,
      holeFillPx: 16,
      sortLayersBy: "area",
      fillStrokeWidth: 1.8,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "mascot-fill-outline",
    label: "Mascot Fill + Outline",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 20,
      requestedPaletteCount: 20,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1500,
      minRegionPercent: 0.06,
      layerOptTolerance: 0.36,
      layerTurdSize: 3,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 7,
      minIslandPx: 8,
      holeFillPx: 7,
      sortLayersBy: "area",
      fillStrokeWidth: 2.1,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "cute-character-fill-ink",
    label: "Cute Character Fill + Ink",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 18,
      requestedPaletteCount: 18,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1450,
      minRegionPercent: 0.07,
      layerOptTolerance: 0.44,
      layerTurdSize: 3,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 8,
      minIslandPx: 9,
      holeFillPx: 8,
      sortLayersBy: "area",
      fillStrokeWidth: 1.7,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "icon-fill-stroke",
    label: "Icon Fill + Stroke",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 8,
      requestedPaletteCount: 8,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 0.8,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1250,
      minRegionPercent: 0.18,
      layerOptTolerance: 0.48,
      layerTurdSize: 4,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 5,
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 18,
      minIslandPx: 12,
      holeFillPx: 10,
      sortLayersBy: "area",
      fillStrokeWidth: 1.4,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "logo-color-ink-outline",
    label: "Logo Color + Ink Outline",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 10,
      requestedPaletteCount: 10,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 0.9,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1300,
      minRegionPercent: 0.12,
      layerOptTolerance: 0.42,
      layerTurdSize: 3,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 10,
      minIslandPx: 8,
      holeFillPx: 8,
      sortLayersBy: "area",
      fillStrokeWidth: 1.5,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "transparent-logo-smooth-color",
    label: "Transparent Logo Smooth Color",
    category: "layered",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 6,
      requestedPaletteCount: 6,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 0.8,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "bt709",
      layerMaxTraceSide: 1250,
      minRegionPercent: 0.2,
      layerOptTolerance: 0.64,
      layerTurdSize: 6,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 6,
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 22,
      minIslandPx: 16,
      holeFillPx: 14,
      sortLayersBy: "area",
    },
  },
  {
    id: "app-icon-smooth-color",
    label: "App Icon Smooth Color",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 8,
      requestedPaletteCount: 8,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 0.9,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1300,
      minRegionPercent: 0.14,
      layerOptTolerance: 0.58,
      layerTurdSize: 5,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 5,
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 18,
      minIslandPx: 14,
      holeFillPx: 14,
      sortLayersBy: "area",
    },
  },
  {
    id: "web-icon-flat-color",
    label: "Web Icon Flat Color",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 6,
      requestedPaletteCount: 6,
      layerBuildMode: "per-color-cutout",
      layerOverlapPx: 0,
      gapFill: "close-small-gaps",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "bt709",
      layerMaxTraceSide: 1150,
      minRegionPercent: 0.18,
      layerOptTolerance: 0.52,
      layerTurdSize: 5,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 6,
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 22,
      minIslandPx: 14,
      holeFillPx: 12,
      sortLayersBy: "area",
    },
  },
  {
    id: "poster-soft-8-color",
    label: "Poster Soft 8 Color",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 8,
      requestedPaletteCount: 8,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1450,
      minRegionPercent: 0.16,
      layerOptTolerance: 0.68,
      layerTurdSize: 7,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 4,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 20,
      minIslandPx: 18,
      holeFillPx: 18,
      sortLayersBy: "area",
    },
  },
  {
    id: "poster-smooth-12-color",
    label: "Poster Smooth 12 Color",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 12,
      requestedPaletteCount: 12,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1500,
      minRegionPercent: 0.1,
      layerOptTolerance: 0.56,
      layerTurdSize: 5,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 4,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 14,
      minIslandPx: 14,
      holeFillPx: 14,
      sortLayersBy: "area",
    },
  },
  {
    id: "comic-poster-color",
    label: "Comic Poster Color",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 10,
      requestedPaletteCount: 10,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1350,
      minRegionPercent: 0.11,
      layerOptTolerance: 0.5,
      layerTurdSize: 4,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 5,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 12,
      minIslandPx: 12,
      holeFillPx: 10,
      edgeThickness: 2,
      sortLayersBy: "area",
      fillStrokeWidth: 1.8,
      fillStrokeColor: "#020617",
    },
  },
  {
    id: "ui-screenshot-clean-regions",
    label: "UI Screenshot Clean Regions",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 18,
      requestedPaletteCount: 18,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 0.8,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1500,
      minRegionPercent: 0.05,
      layerOptTolerance: 0.34,
      layerTurdSize: 2,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 7,
      minIslandPx: 6,
      holeFillPx: 8,
      sortLayersBy: "area",
    },
  },
  {
    id: "dashboard-screenshot-simplified",
    label: "Dashboard Screenshot Simplified",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 12,
      requestedPaletteCount: 12,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 0.9,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1400,
      minRegionPercent: 0.12,
      layerOptTolerance: 0.46,
      layerTurdSize: 4,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 5,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 16,
      minIslandPx: 12,
      holeFillPx: 12,
      sortLayersBy: "area",
    },
  },
  {
    id: "product-mockup-flat-color",
    label: "Product Mockup Flat Color",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 10,
      requestedPaletteCount: 10,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1350,
      minRegionPercent: 0.14,
      layerOptTolerance: 0.58,
      layerTurdSize: 5,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 5,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 16,
      minIslandPx: 14,
      holeFillPx: 14,
      sortLayersBy: "area",
    },
  },
  {
    id: "alpha-safe-layered-color",
    label: "Alpha-Safe Layered Color",
    category: "layered",
    backendIntensity: "very-slow",
    settings: {
      traceMode: "layered",
      colorLayerCount: 10,
      requestedPaletteCount: 10,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 1,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "ciede2000",
      layerMaxTraceSide: 1350,
      minRegionPercent: 0.1,
      layerOptTolerance: 0.48,
      layerTurdSize: 4,
      layerTurnPolicy: "majority",
      posterize: false,
      removeWhite: false,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 10,
      minIslandPx: 10,
      holeFillPx: 10,
      sortLayersBy: "area",
    },
  },
  {
    id: "remove-white-smooth-color",
    label: "Remove White Smooth Color",
    category: "layered",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "layered",
      colorLayerCount: 8,
      requestedPaletteCount: 8,
      layerBuildMode: "stacked-overlap",
      layerOverlapPx: 0.9,
      gapFill: "overlap",
      groupBy: "color",
      paletteAlgorithm: "image-q-wuquant",
      paletteDistance: "bt709",
      layerMaxTraceSide: 1300,
      minRegionPercent: 0.16,
      layerOptTolerance: 0.62,
      layerTurdSize: 6,
      layerTurnPolicy: "majority",
      posterize: true,
      posterizeStrength: 6,
      removeWhite: true,
      removeTransparent: true,
      transparent: true,
      colorMergeTolerance: 18,
      minIslandPx: 16,
      holeFillPx: 14,
      sortLayersBy: "area",
    },
  },
];

export const STROKE_TRACE_PRESET_ADDITIONS: AddedPreset[] = [
  {
    id: "stroke-trace-clean-lines",
    label: "Stroke Trace - Clean Lines",
    category: "stroke",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 204,
        turdSize: 4,
      optTolerance: 0.35,
        lineColor: "#000000",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 16,
        edgeThickness: 2,
        centerlineMaxTraceSide: 1000,
        centerlineStrokeWidth: 2,
        centerlineSimplifyTolerance: 1.3,
        centerlineMinPathLength: 8,
    },
  },
  {
    id: "stroke-trace-bold-lines",
    label: "Stroke Trace - Bold Lines",
    category: "stroke",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 210,
        turdSize: 5,
      optTolerance: 0.42,
        lineColor: "#000000",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 14,
        edgeThickness: 2,
        centerlineMaxTraceSide: 950,
        centerlineStrokeWidth: 4,
        centerlineSimplifyTolerance: 1.5,
        centerlineMinPathLength: 10,
    },
  },
  {
    id: "centerline-sketch",
    label: "Centerline Sketch",
    category: "stroke",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
      threshold: 214,
        turdSize: 4,
      optTolerance: 0.22,
        lineColor: "#111827",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 14,
        edgeThickness: 2,
        centerlineMaxTraceSide: 1050,
        centerlineStrokeWidth: 1.4,
        centerlineSimplifyTolerance: 1.2,
        centerlineMinPathLength: 8,
    },
  },
  {
    id: "single-line-drawing",
    label: "Single-Line Drawing",
    category: "stroke",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 204,
        turdSize: 6,
      optTolerance: 0.55,
        lineColor: "#000000",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 20,
        edgeThickness: 2,
      centerlineMaxTraceSide: 900,
      centerlineStrokeWidth: 2.2,
        centerlineSimplifyTolerance: 2.5,
        centerlineMinPathLength: 14,
    },
  },
  {
    id: "technical-outline-stroke",
    label: "Technical Outline Stroke",
    category: "stroke",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 190,
        turdSize: 4,
      optTolerance: 0.24,
        lineColor: "#0f172a",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 18,
        edgeThickness: 2,
        centerlineMaxTraceSide: 1000,
        centerlineStrokeWidth: 1.2,
        centerlineSimplifyTolerance: 1.0,
        centerlineMinPathLength: 12,
    },
  },
  {
    id: "hand-drawn-stroke",
    label: "Hand-Drawn Stroke",
    category: "stroke",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
      threshold: 218,
        turdSize: 5,
      optTolerance: 0.28,
        lineColor: "#111827",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 14,
        edgeThickness: 2,
        centerlineMaxTraceSide: 1050,
        centerlineStrokeWidth: 2.6,
        centerlineSimplifyTolerance: 1.4,
        centerlineMinPathLength: 8,
    },
  },
  {
    id: "inked-linework-stroke",
    label: "Inked Linework Stroke",
    category: "stroke",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
      threshold: 198,
      turdSize: 5,
      optTolerance: 0.25,
      lineColor: "#020617",
      invert: false,
      transparent: true,
      preprocess: "edge",
      edgeThreshold: 13,
      edgeThickness: 2,
      centerlineMaxTraceSide: 1330,
      centerlineStrokeWidth: 3.1,
      centerlineSimplifyTolerance: 1.05,
      centerlineMinPathLength: 8,
    },
  },
  {
    id: "crisp-cartoon-stroke",
    label: "Crisp Cartoon Stroke",
    category: "stroke",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
      threshold: 190,
      turdSize: 6,
      optTolerance: 0.28,
      lineColor: "#020617",
      invert: false,
      transparent: true,
      preprocess: "edge",
      edgeThreshold: 16,
      edgeThickness: 2,
      centerlineMaxTraceSide: 1330,
      centerlineStrokeWidth: 3.2,
      centerlineSimplifyTolerance: 1.35,
      centerlineMinPathLength: 11,
    },
  },
  {
    id: "clean-ink-centerline",
    label: "Clean Ink Centerline",
    category: "stroke",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 156,
        turdSize: 5,
      optTolerance: 0.3,
        lineColor: "#020617",
        invert: false,
        transparent: true,
        preprocess: "ink-stroke",
        edgeThreshold: 15,
        edgeThickness: 2,
        centerlineMaxTraceSide: 1250,
        centerlineStrokeWidth: 3,
        centerlineSimplifyTolerance: 1.45,
        centerlineMinPathLength: 10,
    },
  },
  {
    id: "high-fidelity-ink-stroke",
    label: "High-Fidelity Ink Stroke",
    category: "stroke",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 204,
        turdSize: 4,
      optTolerance: 0.22,
        lineColor: "#020617",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 12,
        edgeThickness: 2,
        centerlineMaxTraceSide: 1250,
        centerlineStrokeWidth: 2.2,
        centerlineSimplifyTolerance: 1,
        centerlineMinPathLength: 8,
    },
  },
  {
    id: "smooth-centerline",
    label: "Smooth Centerline",
    category: "stroke",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 204,
        turdSize: 6,
      optTolerance: 0.5,
        lineColor: "#000000",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 18,
        edgeThickness: 2,
        centerlineMaxTraceSide: 900,
        centerlineStrokeWidth: 2,
        centerlineSimplifyTolerance: 2.2,
        centerlineMinPathLength: 12,
    },
  },
  {
    id: "minimal-plotter-stroke",
    label: "Minimal Plotter Stroke",
    category: "stroke",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 186,
        turdSize: 8,
      optTolerance: 0.7,
        lineColor: "#000000",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 24,
        edgeThickness: 2,
        centerlineMaxTraceSide: 760,
        centerlineStrokeWidth: 1,
        centerlineSimplifyTolerance: 4,
        centerlineMinPathLength: 22,
    },
  },
  {
    id: "rounded-outline-stroke",
    label: "Rounded Outline Stroke",
    category: "stroke",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 202,
        turdSize: 6,
      optTolerance: 0.45,
        lineColor: "#000000",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 18,
        edgeThickness: 2,
        centerlineMaxTraceSide: 900,
        centerlineStrokeWidth: 4.5,
        centerlineSimplifyTolerance: 2,
        centerlineMinPathLength: 12,
    },
  },
  {
    id: "fine-pen-centerline",
    label: "Fine Pen Centerline",
    category: "stroke",
    backendIntensity: "slow-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 216,
        turdSize: 4,
      optTolerance: 0.18,
        lineColor: "#020617",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 12,
        edgeThickness: 2,
        centerlineMaxTraceSide: 1000,
        centerlineStrokeWidth: 0.9,
        centerlineSimplifyTolerance: 1.0,
        centerlineMinPathLength: 8,
    },
  },
  {
    id: "diagram-centerline-stroke",
    label: "Diagram Centerline Stroke",
    category: "stroke",
    backendIntensity: "low-speed",
    settings: {
      traceMode: "single",
      strokeOutputMode: "centerline",
        threshold: 194,
        turdSize: 5,
      optTolerance: 0.3,
        lineColor: "#0f172a",
        invert: false,
        transparent: true,
        preprocess: "edge",
        edgeThreshold: 18,
        edgeThickness: 2,
        centerlineMaxTraceSide: 1000,
        centerlineStrokeWidth: 1.6,
        centerlineSimplifyTolerance: 1.2,
        centerlineMinPathLength: 12,
    },
  },
];

export const ALL_PRESET_ADDITIONS: AddedPreset[] = [
  ...TRACE_PRESET_ADDITIONS,
  ...STROKE_TRACE_PRESET_ADDITIONS,
];

export const LAYERED_PRESET_ADDITIONS: AddedPreset[] = TRACE_PRESET_ADDITIONS.filter(
  (preset) => preset.category === "layered",
);
export function extendTracePresets<TPreset>(
  presets: readonly TPreset[],
  options: { includeStrokePresets?: boolean } = {},
): TPreset[] {
  return [
    ...presets,
    ...(TRACE_PRESET_ADDITIONS as unknown as TPreset[]),
    ...(options.includeStrokePresets
      ? (STROKE_TRACE_PRESET_ADDITIONS as unknown as TPreset[])
      : []),
  ];
}

export function extendLayeredPresets<TPreset>(
  presets: readonly TPreset[],
): TPreset[] {
  return [...presets, ...(LAYERED_PRESET_ADDITIONS as unknown as TPreset[])];
}
