import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("api/batch-svg", "routes/api.batch-svg.tsx"),

  // Documentation
  route("how-it-works", "routes/how-it-works.tsx"),
  route(
    "how-it-works/conversion-workflow",
    "routes/how-it-works.conversion-workflow.tsx",
  ),
  route("how-it-works/presets", "routes/how-it-works.presets.tsx"),
  route("how-it-works/settings", "routes/how-it-works.settings.tsx"),
  route(
    "how-it-works/troubleshooting",
    "routes/how-it-works.troubleshooting.tsx",
  ),
  route(
    "how-it-works/exporting-and-downloads",
    "routes/how-it-works.exporting-and-downloads.tsx",
  ),
  route("pro-waitlist", "routes/pro-waitlist.tsx"),

  // SVG -> raster/pdf
  route("svg-to-png-converter", "routes/svg-to-png-converter.tsx"),
  route("svg-to-jpg-converter", "routes/svg-to-jpg-converter.tsx"),
  route("svg-to-webp-converter", "routes/svg-to-webp-converter.tsx"),
  route("svg-to-pdf-converter", "routes/svg-to-pdf-converter.tsx"),

  // SVG utilities
  route("svg-background-editor", "routes/svg-background-editor.tsx"),
  route(
    "svg-resize-and-scale-editor",
    "routes/svg-resize-and-scale-editor.tsx",
  ),
  route("svg-recolor", "routes/svg-recolor.tsx"),
  route("svg-minifier", "routes/svg-minifier.tsx"),
  route("svg-cleaner", "routes/svg-cleaner.tsx"),
  route("svg-preview-viewer", "routes/svg-preview-viewer.tsx"),
  route("svg-embed-code-generator", "routes/svg-embed-code-generator.tsx"),
  route("inline-svg-vs-img", "routes/inline-svg-vs-img.tsx"),
  route("svg-to-favicon-generator", "routes/svg-to-favicon-generator.tsx"),
  route("svg-stroke-width-editor", "routes/svg-stroke-width-editor.tsx"),
  route("svg-flip-and-rotate-editor", "routes/svg-flip-and-rotate-editor.tsx"),
  route("svg-dimensions-inspector", "routes/svg-dimensions-inspector.tsx"),
  route("svg-file-size-inspector", "routes/svg-file-size-inspector.tsx"),
  route(
    "svg-accessibility-and-contrast-checker",
    "routes/svg-accessibility-and-contrast-checker.tsx",
  ),
  route("jpeg-to-svg-for-cricut", "routes/jpeg-to-svg-for-cricut.tsx"),

  //US target audience routes
  route("png-to-svg-for-cricut", "routes/png-to-svg-for-cricut.tsx"),
  route(
    "png-to-layered-svg-for-cricut",
    "routes/png-to-layered-svg-for-cricut.tsx",
  ),
  route(
    "png-to-svg-for-cricut-print-then-cut",
    "routes/png-to-svg-for-cricut-print-then-cut.tsx",
  ),
  route(
    "png-to-svg-for-cricut-vinyl",
    "routes/png-to-svg-for-cricut-vinyl.tsx",
  ),
  route(
    "png-to-svg-for-cricut-stickers",
    "routes/png-to-svg-for-cricut-stickers.tsx",
  ),
  route(
    "png-to-svg-for-laser-cutting",
    "routes/png-to-svg-for-laser-cutting.tsx",
  ),
  route("png-to-svg-for-etsy", "routes/png-to-svg-for-etsy.tsx"),
  route("png-to-svg-for-silhouette", "routes/png-to-svg-for-silhouette.tsx"),
  route("logo-to-svg-for-cricut", "routes/logo-to-svg-for-cricut.tsx"),
  route("cricut-svg-converter", "routes/cricut-svg-converter.tsx"),
  route("image-to-svg-for-cricut", "routes/image-to-svg-for-cricut.tsx"),
  route("jpg-to-svg-for-cricut", "routes/jpg-to-svg-for-cricut.tsx"),
  route("webp-to-svg-for-cricut", "routes/webp-to-svg-for-cricut.tsx"),
  route("photo-to-svg-for-cricut", "routes/photo-to-svg-for-cricut.tsx"),
  route(
    "black-and-white-image-to-svg-for-cricut",
    "routes/black-and-white-image-to-svg-for-cricut.tsx",
  ),
  route("line-art-to-svg-for-cricut", "routes/line-art-to-svg-for-cricut.tsx"),
  route("drawing-to-svg-for-cricut", "routes/drawing-to-svg-for-cricut.tsx"),
  route("sketch-to-svg-for-cricut", "routes/sketch-to-svg-for-cricut.tsx"),
  route("sticker-to-svg-for-cricut", "routes/sticker-to-svg-for-cricut.tsx"),
  route("base64-to-svg-for-cricut", "routes/base64-to-svg-for-cricut.tsx"),
  route("code-to-svg-for-cricut", "routes/code-to-svg-for-cricut.tsx"),
  route("layered-svg-for-cricut", "routes/layered-svg-for-cricut.tsx"),
  route(
    "image-to-layered-svg-for-cricut",
    "routes/image-to-layered-svg-for-cricut.tsx",
  ),
  route(
    "jpg-to-layered-svg-for-cricut",
    "routes/jpg-to-layered-svg-for-cricut.tsx",
  ),
  route(
    "logo-to-layered-svg-for-cricut",
    "routes/logo-to-layered-svg-for-cricut.tsx",
  ),

  // Base64
  route("svg-to-base64", "routes/svg-to-base64.tsx"),
  route("base64-to-svg", "routes/base64-to-svg.tsx"),

  // Color tool
  route("free-color-picker", "routes/free-color-picker.tsx"),

  // Raster -> SVG
  route("png-to-svg-converter", "routes/png-to-svg-converter.tsx"),
  route("jpg-to-svg-converter", "routes/jpg-to-svg-converter.tsx"),
  route("jpeg-to-svg-converter", "routes/jpeg-to-svg-converter.tsx"),
  route("webp-to-svg-converter", "routes/webp-to-svg-converter.tsx"),
  route("logo-to-svg-converter", "routes/logo-to-svg-converter.tsx"),
  route("icon-to-svg-converter", "routes/icon-to-svg-converter.tsx"),
  route("emoji-to-svg-converter", "routes/emoji-to-svg-converter.tsx"),
  route("text-to-svg-converter", "routes/text-to-svg-converter.tsx"),
  route("sticker-to-svg-converter", "routes/sticker-to-svg-converter.tsx"),
  route("line-art-to-svg-converter", "routes/line-art-to-svg-converter.tsx"),
  route("drawing-to-svg-converter", "routes/drawing-to-svg-converter.tsx"),
  route("scan-to-svg-converter", "routes/scan-to-svg-converter.tsx"),
  route("sketch-to-svg-converter", "routes/sketch-to-svg-converter.tsx"),
  route("image-to-svg-outline", "routes/image-to-svg-outline.tsx"),
  route("photo-to-svg-outline", "routes/photo-to-svg-outline.tsx"),
  route(
    "black-and-white-image-to-svg-converter",
    "routes/black-and-white-image-to-svg-converter.tsx",
  ),

  // Route expansion and consolidated intent routes
  route("gif-to-svg-converter", "routes/gif-to-svg-converter.tsx"),
  route("avif-to-svg-converter", "routes/avif-to-svg-converter.tsx"),
  route("bmp-to-svg-converter", "routes/bmp-to-svg-converter.tsx"),
  route("tiff-to-svg-converter", "routes/tiff-to-svg-converter.tsx"),
  route("tif-to-svg-converter", "routes/tif-to-svg-converter.tsx"),
  route("image-to-svg-converter", "routes/image-to-svg-converter.tsx"),
  route("black-and-white-png-to-svg-converter", "routes/black-and-white-png-to-svg-converter.tsx"),
  route("svg-to-ico-converter", "routes/svg-to-ico-converter.tsx"),
  route("image-to-favicon-generator", "routes/image-to-favicon-generator.tsx"),
  route("png-to-favicon-generator", "routes/png-to-favicon-generator.tsx"),
  route("jpg-to-favicon-generator", "routes/jpg-to-favicon-generator.tsx"),
  route("logo-to-favicon-generator", "routes/logo-to-favicon-generator.tsx"),
  route("png-to-ico-converter", "routes/png-to-ico-converter.tsx"),
  route("png-to-svg-for-shopify", "routes/png-to-svg-for-shopify.tsx"),
  route("logo-to-svg-for-shopify", "routes/logo-to-svg-for-shopify.tsx"),
  route("svg-to-png-for-shopify", "routes/svg-to-png-for-shopify.tsx"),
  route("svg-to-favicon-for-shopify", "routes/svg-to-favicon-for-shopify.tsx"),
  route("svg-resizer-for-shopify", "routes/svg-resizer-for-shopify.tsx"),
  route("logo-to-favicon-for-shopify", "routes/logo-to-favicon-for-shopify.tsx"),
  route("svg-to-png-for-etsy", "routes/svg-to-png-for-etsy.tsx"),
  route("svg-to-jpg-for-etsy", "routes/svg-to-jpg-for-etsy.tsx"),
  route("logo-to-svg-for-etsy", "routes/logo-to-svg-for-etsy.tsx"),
  route("sticker-to-svg-for-etsy", "routes/sticker-to-svg-for-etsy.tsx"),
  route("image-to-svg-for-etsy", "routes/image-to-svg-for-etsy.tsx"),
  route("jpg-to-svg-for-etsy", "routes/jpg-to-svg-for-etsy.tsx"),
  route("svg-resizer-for-etsy", "routes/svg-resizer-for-etsy.tsx"),
  route("svg-to-png-for-printify", "routes/svg-to-png-for-printify.tsx"),
  route("svg-to-png-for-printful", "routes/svg-to-png-for-printful.tsx"),
  route("sticker-to-png-for-printing", "routes/sticker-to-png-for-printing.tsx"),
  route("svg-to-transparent-png-for-printing", "routes/svg-to-transparent-png-for-printing.tsx"),
  route("png-to-svg-for-glowforge", "routes/png-to-svg-for-glowforge.tsx"),
  route("jpg-to-svg-for-glowforge", "routes/jpg-to-svg-for-glowforge.tsx"),
  route("logo-to-svg-for-glowforge", "routes/logo-to-svg-for-glowforge.tsx"),
  route("svg-cleaner-for-glowforge", "routes/svg-cleaner-for-glowforge.tsx"),
  route("svg-resizer-for-glowforge", "routes/svg-resizer-for-glowforge.tsx"),
  route("image-to-svg-for-glowforge", "routes/image-to-svg-for-glowforge.tsx"),
  route("jpg-to-svg-for-silhouette", "routes/jpg-to-svg-for-silhouette.tsx"),
  route("image-to-svg-for-silhouette", "routes/image-to-svg-for-silhouette.tsx"),
  route("logo-to-svg-for-silhouette", "routes/logo-to-svg-for-silhouette.tsx"),
  route("sticker-to-svg-for-silhouette", "routes/sticker-to-svg-for-silhouette.tsx"),
  route("svg-cleaner-for-silhouette", "routes/svg-cleaner-for-silhouette.tsx"),
  route("svg-resizer-for-silhouette", "routes/svg-resizer-for-silhouette.tsx"),
  route("png-to-svg-for-canva", "routes/png-to-svg-for-canva.tsx"),
  route("jpg-to-svg-for-canva", "routes/jpg-to-svg-for-canva.tsx"),
  route("svg-to-png-for-canva", "routes/svg-to-png-for-canva.tsx"),
  route("logo-to-svg-for-canva", "routes/logo-to-svg-for-canva.tsx"),
  route("svg-resizer-for-canva", "routes/svg-resizer-for-canva.tsx"),
  route("svg-cleaner-for-figma", "routes/svg-cleaner-for-figma.tsx"),
  route("svg-resizer-for-figma", "routes/svg-resizer-for-figma.tsx"),
  route("svg-to-png-for-figma", "routes/svg-to-png-for-figma.tsx"),
  route("png-to-svg-for-figma", "routes/png-to-svg-for-figma.tsx"),
  route("svg-to-jsx-converter", "routes/svg-to-jsx-converter.tsx"),
  route("svg-to-react-component", "routes/svg-to-react-component.tsx"),
  route("svg-to-css-background", "routes/svg-to-css-background.tsx"),
  route("svg-to-data-uri-converter", "routes/svg-to-data-uri-converter.tsx"),
  route("svg-inline-code-generator", "routes/svg-inline-code-generator.tsx"),
  route("svg-viewbox-editor", "routes/svg-viewbox-editor.tsx"),
  route("svg-code-cleaner", "routes/svg-code-cleaner.tsx"),
  route("image-to-layered-svg-converter", "routes/image-to-layered-svg-converter.tsx"),
  route("jpg-to-layered-svg-converter", "routes/jpg-to-layered-svg-converter.tsx"),
  route("logo-to-layered-svg-converter", "routes/logo-to-layered-svg-converter.tsx"),
  route("transparent-png-to-svg-converter", "routes/transparent-png-to-svg-converter.tsx"),
  route("svg-transparent-background-tool", "routes/svg-transparent-background-tool.tsx"),

  // Legal
  route("cookies", "routes/cookies.tsx"),
  route("privacy-policy", "routes/privacy-policy.tsx"),
  route("terms-of-service", "routes/terms-of-service.tsx"),
  route("sitemap", "routes/sitemap.tsx"),
] satisfies RouteConfig;
